analyzer:
  errors:
    avoid_unnecessary_containers: ignore
    must_be_immutable: ignore
    unused_element: ignore
    unused_local_variable: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_print: false
    prefer_single_quotes: true
    use_build_context_synchronously: true
    file_names: false
