name: todo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_local_notifications: ^17.1.2
  flutter_native_timezone:
    path: C:/Users/joee9/flutter projects/App10-To Do/flutter_native_timezone-master
  intl: ^0.19.0
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  sqflite: ^2.3.3+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  rxdart: ^0.27.7
  timezone: ^0.9.3
  flutter_datetime_picker_plus: ^2.1.0
  animated_text_kit: ^4.2.1
  flutter_colorpicker: ^1.0.3
  scroll_date_picker: ^3.8.0
  scroll_wheel_date_picker: ^0.0.2+1
  uuid: ^4.4.0
  easy_splash_screen: ^1.0.4
  tutorial_coach_mark: ^1.2.11
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/myappicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/myappicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/myappicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/myappicon.png"

flutter:
  uses-material-design: true

  assets:
    - images/Liste.svg
    - images/myappicon.png
